document.addEventListener('DOMContentLoaded',()=>{
  const state={type:'events',query:'',sort:'default',page:1,perPage:6,data:[]};
  const els={grid:document.getElementById('dataGrid'),search:document.getElementById('dataSearch'),sort:document.getElementById('dataSort'),count:document.getElementById('dataCount'),pages:document.getElementById('pagination'),title:document.getElementById('dataTitle'),empty:document.getElementById('dataEmpty')};
  const files={events:'data/events.json',profiles:'data/profiles.json',notices:'data/notices.json',faqs:'data/faqs.json'};
  const labels={events:'Campus Events',profiles:'Student Profiles',notices:'Campus Notices',faqs:'Frequently Asked Questions'};
  const load=async type=>{state.type=type;state.page=1;state.query='';els.search.value='';state.sort='default';els.sort.value='default';els.title.textContent=labels[type];try{const r=await fetch(files[type]);if(!r.ok)throw new Error('Fetch failed');state.data=await r.json();render()}catch(e){els.grid.innerHTML='<div class="alert alert-warning">Unable to load JSON data. Run this project with VS Code Live Server or a web server.</div>'}};
  const filtered=()=>{let a=state.data.filter(x=>JSON.stringify(x).toLowerCase().includes(state.query.toLowerCase()));if(state.sort!=='default')a.sort((x,y)=>{const k=state.sort==='name'?'name':state.sort==='date'?'date':'title';return String(x[k]||'').localeCompare(String(y[k]||''))});return a};
  const card=(x)=>{if(state.type==='events')return `<div class="col-md-6 col-xl-4"><article class="data-card"><span class="notice-tag blue">EVENT</span><h4>${x.title}</h4><p>${x.description}</p><small><i class="fa-regular fa-calendar"></i> ${x.date} • ${x.venue}</small></article></div>`;
    if(state.type==='profiles')return `<div class="col-md-6 col-xl-4"><article class="data-card"><div class="data-avatar">${x.name[0]}</div><h4>${x.name}</h4><p>${x.course} • Semester ${x.semester}</p><small>${x.email}</small></article></div>`;
    if(state.type==='notices')return `<div class="col-md-6 col-xl-4"><article class="data-card"><span class="notice-tag green">NOTICE</span><h4>${x.title}</h4><p>${x.message}</p><small><i class="fa-regular fa-calendar"></i> ${x.date}</small></article></div>`;
    return `<div class="col-12"><article class="data-card faq-data"><h4>${x.question}</h4><p>${x.answer}</p></article></div>`};
  const render=()=>{const a=filtered(),pages=Math.max(1,Math.ceil(a.length/state.perPage));state.page=Math.min(state.page,pages);const start=(state.page-1)*state.perPage;els.grid.innerHTML=a.length?a.slice(start,start+state.perPage).map(card).join(''):'<div class="col-12"><div class="empty-state" id="dataEmpty">No matching records found.</div></div>';els.count.textContent=`Showing ${a.length?start+1:0}-${Math.min(start+state.perPage,a.length)} of ${a.length}`;els.pages.innerHTML=Array.from({length:pages},(_,i)=>`<button class="btn btn-sm ${i+1===state.page?'btn-primary':'btn-light'}" data-page="${i+1}">${i+1}</button>`).join('');els.pages.querySelectorAll('button').forEach(b=>b.onclick=()=>{state.page=+b.dataset.page;render()})};
  document.querySelectorAll('.data-tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.data-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');load(b.dataset.type)});
  els.search.oninput=e=>{state.query=e.target.value;state.page=1;render()};els.sort.onchange=e=>{state.sort=e.target.value;state.page=1;render()};load('events');
});
